/**
 * Flat dotted-key defaults — the "default (in code)" layer of SPEC.md
 * §11.1's resolution order (default -> org override -> event override ->
 * locale -> rendered). Every `t('some.key')` call anywhere in this app
 * must have an entry here; scripts/check-copy-keys.mjs fails the build
 * otherwise. Keys are namespaced by screen, per §11.1.
 *
 * Kept to exactly what the app's UI actually calls — add a key in the
 * same commit as the code that calls it, per SPEC.md §11.1, rather than
 * staging strings ahead of the screens that will use them.
 */
export const en = {
  "brand.name": "Rounds",
  "app.loading": "Loading…",
  "app.error.title": "Something went wrong",
  "app.error.body": "This page hit an error. Try again — if it keeps happening, let us know what you were doing.",
  "app.error.retry": "Try again",

  "auth.signIn.cta": "Sign in",
  "nav.admin": "Admin",

  "previewer.landing.title": "Find a service event near you",
  "previewer.landing.subtitle":
    "Sign in to browse events, or enter a key if someone gave you one.",


  "previewer.emptyState.title": "No events published yet",
  "previewer.emptyState.body":
    "When an organizer publishes an event, it'll show up here. Have an invite key? Look for \"Have a key?\" once events are live.",

  "signup.stepper.holidays": "Holidays",
  "signup.stepper.address": "Address",
  "signup.stepper.pay": "Pay",
  "signup.holidays.title": "Which holidays this year?",
  "signup.holidays.subtitle":
    "Pick as many as you like. A volunteer sets your flag out before sunrise and collects it that evening.",
  "signup.holidays.mostPopular": "Most popular",
  "signup.holidays.selectedCount":
    "{count, plural, one {# holiday selected} other {# holidays selected}}",
  "signup.holidays.continue": "Continue",
  "signup.loading": "Loading…",
  "signup.error.title": "Something went wrong",
  "signup.error.body": "We hit an error loading this page. Nothing you entered has been lost — try again.",
  "signup.error.retry": "Try again",
  "signup.notFound.title": "Signups aren't open right now",
  "signup.notFound.body": "Check back soon, or ask your organizer for the current signup link.",

  "dashboard.greeting": "You're signed in as {{role}}.",
  "dashboard.manageUsers.title": "Manage user roles",
  "dashboard.manageUsers.body": "Add someone's email and set their role — it applies the next time they sign in.",
  "dashboard.manageUsers.cta": "Manage users",

  "admin.users.title": "Users",
  "admin.users.subtitle": "Set a role for an email address. If they haven't signed in yet, their first Google sign-in will pick it up.",
  "admin.users.form.email": "Email",
  "admin.users.form.role": "Role",
  "admin.users.form.submit": "Save role",
  "admin.users.form.ownerRestricted": "Only an Owner can grant the Owner role.",
  "admin.users.table.email": "Email",
  "admin.users.table.name": "Name",
  "admin.users.table.role": "Role",
  "admin.users.table.updated": "Last updated",
  "admin.users.empty": "No users yet.",

  "auth.createAccount.cta": "Sign in with email + password",

  "register.title": "Email + password",
  "register.subtitle": "Already have an account with this email? Just enter your password to sign in. New here? This creates your account.",
  "register.afterSignup.title": "Create your account",
  "register.afterSignup.subtitle": "We've filled in what you just told us — just set a password to save it for next year.",
  "register.form.name": "Name",
  "register.form.email": "Email",
  "register.form.password": "Password (10+ characters for a new account)",
  "register.form.confirmPassword": "Confirm password",
  "register.form.confirmPasswordHint": "Only needed if you're creating a new account.",
  "register.form.submit": "Continue",
  "register.form.submitting": "Working…",
  "register.error.mismatch": "Passwords don't match.",
  "register.error.generic": "Something went wrong. Try again.",

  "account.signOut.cta": "Sign out",
  "account.switchAccount.cta": "Switch / add account",

  "landing.imagePlaceholder.caption": "Photos from real events show up here once an organizer adds them",
  "landing.howItWorks.title": "How it works",
  "landing.howItWorks.step1.title": "Find an event",
  "landing.howItWorks.step1.body": "Browse service events an organizer has published near you.",
  "landing.howItWorks.step2.title": "Sign up in minutes",
  "landing.howItWorks.step2.body": "Pick your options, and you're on the list — no account required to browse.",
  "landing.howItWorks.step3.title": "A volunteer handles the rest",
  "landing.howItWorks.step3.body": "Someone from the organizing team takes care of it, and you'll get updates along the way.",

  "preview.label": "View as",
  "preview.real": "Yourself",
  "preview.banner": "Previewing as {{role}} — this doesn't change your real permissions. Any admin actions here still use your real account.",
  "preview.forbidden.title": "Not visible to {{role}}",
  "preview.forbidden.body": "This page is admin-only, so a real {{role}} account never sees it — they'd land on the home screen instead. Go there to see exactly what they'd see.",
  "preview.forbidden.backHome": "Go to the home screen as {{role}}",

  "signup.address.title": "Where should we set up?",
  "signup.address.subtitle": "Start typing your address and pick it from the list. Drag the pin on the map if it's not quite right.",
  "signup.address.label": "Street address",
  "signup.address.placeholder": "Start typing your address…",
  "signup.address.searching": "Searching…",
  "signup.address.dragHint": "Drag the pin if it's not quite right — that's exactly where we'll come.",
  "signup.address.useAsTyped": "Can't find it in the list? Use the address as typed",
  "signup.address.pinAt": "Pin is at: {{address}}",
  "signup.address.pinMovedNoAddress": "Pin moved — address unavailable for this exact spot.",
  "signup.address.back": "Back",
  "signup.address.continue": "Continue",
  "signup.address.required": "Choose an address to continue.",

  "signup.contact.title": "Almost done",
  "signup.contact.subtitle": "How should we reach you, and anything a volunteer should know?",
  "signup.contact.name": "Full name",
  "signup.contact.email": "Email",
  "signup.contact.phone": "Phone",
  "signup.contact.placementNote": "Where to place the flag",
  "signup.contact.placementNotePlaceholder": "e.g. left of the driveway",
  "signup.contact.accessNotes": "Anything else? (dog, gate code, stairs...)",
  "signup.contact.reviewTitle": "Review",
  "signup.contact.reviewHolidays": "Holidays",
  "signup.contact.reviewAddress": "Address",
  "signup.contact.reviewTotal": "Total",
  "signup.contact.paymentNote": "Payment isn't set up yet — submitting reserves your spot and an organizer will follow up to collect payment.",
  "signup.contact.back": "Back",
  "signup.contact.submit": "Submit",
  "signup.contact.submitting": "Submitting…",
  "signup.contact.required": "Name and address are required.",
  "signup.contact.error": "Something went wrong submitting your signup. Try again.",
  "signup.contact.rateLimited": "Too many signups from this connection in a short time — wait a few minutes and try again.",

  "signup.done.title": "You're on the list",
  "signup.done.body": "We've saved your signup for {{count}} {count, plural, one {holiday} other {holidays}}. An organizer will reach out about payment and details.",
  "signup.done.backHome": "Back to home",
  "signup.done.accountCta.title": "Want to skip the form next time?",
  "signup.done.accountCta.body": "Create a quick account with the info you just entered, and next year you can just sign in — your address and placement note will already be filled in.",
  "signup.done.accountCta.cta": "Create an account",
  "signup.done.accountCta.skip": "No thanks, I'm done",
  "signup.done.selfService.title": "Manage this anytime, no account needed",
  "signup.done.selfService.body": "Bookmark this link — it lets you change holidays, update your address, or cancel, any time. Anyone with the link can use it, so keep it private.",
  "signup.done.selfService.copy": "Copy link",
  "signup.done.selfService.copied": "Copied!",

  "dashboard.manageEvents.title": "Events",
  "dashboard.manageEvents.body": "Generate this year's flag events, or create a one-off event.",
  "dashboard.manageEvents.cta": "Manage events",

  "admin.events.title": "Events",
  "admin.events.currentOrg": "Organization: {{name}}",
  "admin.events.noOrg": "No organization set up yet — creating events below will create one.",


  "admin.events.list.name": "Name",
  "admin.events.list.date": "Date",
  "admin.events.list.status": "Status",
  "admin.events.list.edit": "Edit",

  "admin.events.categories.title": "Categories",
  "admin.events.categories.count": "{count, plural, one {# opportunity} other {# opportunities}}",
  "admin.events.category.subtitle": "Individual opportunities under this category.",
  "admin.events.category.empty": "No opportunities in this category yet — create one above.",

  "admin.eventDetail.back": "← Back to events",
  "admin.eventDetail.stats.signups": "Signups",
  "admin.eventDetail.stats.skipped": "Skipped",
  "admin.eventDetail.stats.total": "Total",
  "admin.eventDetail.export": "Export CSV",
  "admin.eventDetail.export.confirm": "This downloads every household's name, contact info, and address for this event as a CSV file. Continue?",
  "admin.eventDetail.list.title": "Households",
  "admin.eventDetail.list.empty": "No one has signed up for this event yet.",
  "admin.eventDetail.list.name": "Name",
  "admin.eventDetail.list.contact": "Contact",
  "admin.eventDetail.list.address": "Address",
  "admin.eventDetail.list.status": "Status",
  "admin.eventDetail.list.skipped": "Skipped",

  "admin.eventDetail.households.remove": "Remove from event",
  "admin.eventDetail.households.removing": "Removing…",
  "admin.eventDetail.households.removeSuccess": "Removed {{count}} household(s) from this event.",
  "admin.eventDetail.households.copy": "Copy to event",
  "admin.eventDetail.households.copying": "Copying…",
  "admin.eventDetail.households.copySuccess": "Copied {{count}} household(s) into that event.",
  "admin.eventDetail.households.copyTarget": "Copy selected into…",

  "admin.eventDetail.import.title": "Import CSV",
  "admin.eventDetail.import.subtitle": "Bulk-add households to this event, or copy a CSV exported from another event.",

  "admin.eventDetail.stops.title": "Generate stops",
  "admin.eventDetail.stops.subtitle": "Turn every subscribed, non-skipped, reviewed household into a stop for this event. Safe to run again — already-generated stops are skipped, not duplicated.",
  "admin.eventDetail.stops.generate": "Generate stops from subscriptions",
  "admin.eventDetail.stops.generating": "Generating…",
  "admin.eventDetail.stops.result": "{{created}} stop(s) created, {{existed}} already existed.",
  "admin.eventDetail.import.label": "CSV file",
  "admin.eventDetail.import.submit": "Import",
  "admin.eventDetail.import.submitting": "Importing…",
  "admin.eventDetail.import.success": "Imported {{count}} household(s).",
  "admin.eventDetail.import.errorCount": "{{count}} row(s) had a problem and were skipped:",
  "admin.eventDetail.import.errorRow": "Row {{row}}:",

  "admin.eventDetail.people.title": "People on this opportunity",
  "admin.eventDetail.people.subtitle": "Admin/Coordinator/Volunteer access scoped to just this opportunity — the same person can have a different role on a different one.",
  "admin.eventDetail.people.email": "Email",
  "admin.eventDetail.people.role": "Role",
  "admin.eventDetail.people.add": "Add",
  "admin.eventDetail.people.adding": "Adding…",
  "admin.eventDetail.people.empty": "No one has event-level access yet — Owners/Admins already have access to everything.",
  "admin.eventDetail.people.removing": "Removing…",
  "admin.eventDetail.people.removeSelected": "Remove selected",
  "admin.eventDetail.people.removeSuccess": "Removed {{count}} person/people.",
  "admin.eventDetail.people.saveRole": "Save role",
  "admin.eventDetail.people.savingRole": "Saving…",
  "admin.eventDetail.people.roleSaved": "Saved.",

  "admin.loading": "Loading…",
  "admin.error.title": "Something went wrong",
  "admin.error.body": "This page hit an error loading its data. Try again — if it keeps happening, the underlying data or connection may be the issue.",
  "admin.error.retry": "Try again",

  "admin.tabs.nav": "Admin sections",
  "admin.tabs.events": "Events",
  "admin.tabs.library": "Library",
  "admin.tabs.users": "Users",
  "admin.tabs.settings": "Settings",
  "admin.tabs.review": "Review",

  "admin.review.title": "Needs review",
  "admin.review.subtitle": "Addresses that weren't a trusted geocoded pick, or that landed within 25m of another household — check before they become stops.",
  "admin.review.empty": "Nothing needs review right now.",
  "admin.review.table.name": "Name",
  "admin.review.table.address": "Address",
  "admin.review.table.reason": "Why",
  "admin.review.table.submitted": "Submitted",
  "admin.review.markReviewed": "Mark reviewed",
  "admin.review.marking": "Marking…",
  "admin.review.noReason": "No reason recorded",

  "admin.eventDetail.edit.name": "Name",
  "admin.eventDetail.edit.status": "Status",
  "admin.eventDetail.edit.starts": "Starts",
  "admin.eventDetail.edit.ends": "Ends",
  "admin.eventDetail.edit.save": "Save changes",
  "admin.eventDetail.edit.saving": "Saving…",
  "admin.eventDetail.edit.saved": "Saved.",

  "admin.household.title": "Edit household",
  "admin.household.subtitle": "Full record — changes apply everywhere this household is referenced.",
  "admin.household.edit": "Edit",
  "admin.household.name": "Name",
  "admin.household.email": "Email",
  "admin.household.phone": "Phone",
  "admin.household.address": "Address",
  "admin.household.placementNote": "Placement note",
  "admin.household.accessNotes": "Access notes",
  "admin.household.save": "Save changes",
  "admin.household.saving": "Saving…",
  "admin.household.saved": "Saved.",

  "admin.settings.save": "Save",
  "admin.settings.saving": "Saving…",
  "admin.settings.saved": "Saved.",
  "admin.settings.orgTitle": "Organization",
  "admin.settings.orgSubtitle": "The one organization this app serves.",
  "admin.settings.orgName": "Name",
  "admin.settings.emailFrom": "Email \"From\" address",
  "admin.settings.emailFromHint":
    "Used for signup-link emails sent to households. Must be a sender your email provider (Resend) will actually deliver as — leave blank to use the deployment default.",

  "admin.bulk.selectAll": "Select all",

  "admin.users.row.save": "Save",
  "admin.users.row.saving": "Saving…",
  "admin.users.row.saved": "Saved.",

  "admin.users.bulk.deleting": "Deleting…",
  "admin.users.bulk.delete": "Delete selected",
  "admin.users.bulk.success": "Deleted {{count}} user(s).",

  "admin.events.bulk.deleting": "Deleting…",
  "admin.events.bulk.delete": "Delete selected",
  "admin.events.bulk.success": "Deleted {{count}} opportunity/opportunities.",

  "admin.library.title": "Data library",
  "admin.library.subtitle": "Browse every household ever created for this org — sort, hide columns, then copy or delete the ones you want.",
  "admin.library.search.label": "Search",
  "admin.library.search.placeholder": "Name, email, phone, or address",
  "admin.library.search.submit": "Search",
  "admin.library.search.prompt": "Search for a household to get started.",
  "admin.library.search.empty": "No households matched that search.",
  "admin.library.noEvents": "No events exist yet to copy into — create one under Events first.",
  "admin.library.table.name": "Name",
  "admin.library.table.contact": "Contact",
  "admin.library.table.address": "Address",
  "admin.library.table.placementNote": "Placement note",
  "admin.library.table.accessNotes": "Access notes",
  "admin.library.table.created": "Created",
  "admin.library.eventLabel": "Copy into event",
  "admin.library.eventPlaceholder": "Choose an event…",
  "admin.library.copy": "Copy selected",
  "admin.library.copying": "Copying…",
  "admin.library.success": "Copied {{count}} household(s) into that event.",
  "admin.library.delete": "Delete selected",
  "admin.library.deleting": "Deleting…",
  "admin.library.deleteSuccess": "Deleted {{count}} household(s).",
  "admin.library.columns.label": "Columns:",
  "admin.library.total": "{{count}} household(s) total.",
  "admin.library.pagination.prev": "← Previous",
  "admin.library.pagination.next": "Next →",
  "admin.library.pagination.status": "Page {{page}} of {{totalPages}}",

  "selfService.title": "Your subscription",
  "selfService.greeting": "Hi {{name}}",
  "selfService.subtitle": "Manage your flag subscription — no login needed. This link is yours; keep it private.",
  "selfService.saving": "Saving…",
  "selfService.save": "Save",
  "selfService.saved": "Saved.",
  "selfService.address.title": "Address",
  "selfService.address.label": "Current address",
  "selfService.address.change": "Change",
  "selfService.address.cancel": "Cancel",
  "selfService.address.saved": "Saved — a volunteer coordinator will double-check this before it's used for routing.",
  "selfService.address.reviewNote": "Changing your address flags it for a quick human check before it's used for routing — that way a volunteer never gets sent to the wrong place.",
  "selfService.notes.title": "Placement & access notes",
  "selfService.skipped": "Skipped",
  "selfService.undoSkip": "Undo skip",
  "selfService.skipThisOne": "Skip this one",
  "selfService.cancelSubscription": "Cancel this subscription",
  "selfService.cancelConfirm": "Cancel your whole subscription?",
  "selfService.cancelReally": "Yes, cancel",
  "selfService.cancelled": "Cancelled",
  "selfService.notFound.title": "Link not found or expired",
  "selfService.notFound.body": "This self-service link isn't valid anymore. If you think that's wrong, reach out to your organizer.",

  "welcome.title": "What brings you here?",
  "welcome.subtitle": "Pick one to get started — you can always come back to this later.",
  "welcome.customer.title": "I want a service",
  "welcome.customer.body": "Sign up for flag set-out or whatever else is currently open.",
  "welcome.customer.cta": "Go to signup",
  "welcome.volunteer.title": "I want to help organize or volunteer",
  "welcome.volunteer.body": "Coordinator and volunteer access is granted by an organizer, not automatic — let them know you're interested and they'll set you up.",
  "welcome.volunteer.cta": "Continue",
  "welcome.volunteer.thanks": "Thanks! Let an organizer know you're interested in helping, and they'll grant you access.",
} as const;

export type CopyKey = keyof typeof en;
