-- Rounds Phase 0: five-role migration + foundation models (SPEC.md §3.1, §5).
--
-- This file is hand-edited, not raw `prisma migrate dev` output. Two fixes
-- were necessary on top of what Prisma autogenerated from the schema diff:
--
-- 1. `USING ("role"::text::"Role_new")` fails: the old enum's 'USER' value
--    has no counterpart in the new enum, so casting text -> new enum
--    errors on every existing USER row. Replaced with an explicit CASE so
--    ADMIN stays ADMIN and USER becomes PREVIEWER, per SPEC.md §3.1 ("the
--    safe direction — a USER in the old schema has no route assignments
--    and should not silently gain field access").
-- 2. The autogenerated script referenced `ALTER TABLE "Membership" ...`
--    inside the enum-swap transaction, before `Membership` is created
--    later in the same file — it doesn't exist yet at that point and the
--    statement would fail outright. Removed; Membership is created further
--    down already against the correct (renamed) "Role" type, so no
--    separate ALTER is needed for it.

-- CreateEnum
CREATE TYPE "EventKind" AS ENUM ('FLAG_SETOUT', 'FLAG_PICKUP', 'FLYER_DELIVERY', 'FUNDRAISER', 'PICKUP_COLLECTION');

-- CreateEnum
CREATE TYPE "EventStatus" AS ENUM ('DRAFT', 'OPEN', 'CLOSED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "StopSource" AS ENUM ('SUBSCRIPTION', 'SURVEY', 'CSV_IMPORT', 'TERRITORY_FILL', 'MANUAL_PIN', 'CARRIED_OVER', 'FIELD_ADDED');

-- CreateEnum
CREATE TYPE "StopStatus" AS ENUM ('UNASSIGNED', 'ASSIGNED', 'IN_PROGRESS', 'DONE', 'SKIPPED', 'ISSUE');

-- AlterEnum
BEGIN;
CREATE TYPE "Role_new" AS ENUM ('OWNER', 'ADMIN', 'COORDINATOR', 'VOLUNTEER', 'PREVIEWER');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'ADMIN'
    WHEN 'USER' THEN 'PREVIEWER'
  END
)::"Role_new";
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "Role_old";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'PREVIEWER';
COMMIT;

-- CreateTable
CREATE TABLE "Organization" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "branding" JSONB NOT NULL DEFAULT '{}',
    "settings" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "Organization_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Membership" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "role" "Role" NOT NULL,
    "eventId" TEXT,
    "grantedBy" TEXT,
    "grantedViaKeyId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Event" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "seasonId" TEXT,
    "kind" "EventKind" NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" "EventStatus" NOT NULL DEFAULT 'DRAFT',
    "summary" TEXT,
    "descriptionMd" TEXT,
    "coverImageUrl" TEXT,
    "serviceStartsAt" TIMESTAMP(3) NOT NULL,
    "serviceEndsAt" TIMESTAMP(3) NOT NULL,
    "signupsCloseAt" TIMESTAMP(3),
    "timezone" TEXT NOT NULL DEFAULT 'America/Denver',
    "depotLat" DOUBLE PRECISION,
    "depotLng" DOUBLE PRECISION,
    "pairedEventId" TEXT,
    "modules" JSONB NOT NULL,
    "outcomeSet" JSONB NOT NULL,
    "copyOverrides" JSONB,
    "layoutBlocks" JSONB,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Household" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "contactName" TEXT NOT NULL,
    "contactEmail" TEXT,
    "contactPhone" TEXT,
    "addressInput" TEXT NOT NULL,
    "address" JSONB NOT NULL,
    "lat" DOUBLE PRECISION,
    "lng" DOUBLE PRECISION,
    "geocodeConfidence" DOUBLE PRECISION,
    "geocodeSource" TEXT,
    "needsReview" BOOLEAN NOT NULL DEFAULT false,
    "placementNote" TEXT,
    "accessNotes" TEXT,
    "language" TEXT NOT NULL DEFAULT 'en',
    "selfServiceTokenHash" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "Household_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Stop" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "source" "StopSource" NOT NULL,
    "householdId" TEXT,
    "signupId" TEXT,
    "carriedFromStopId" TEXT,
    "routeId" TEXT,
    "sequence" INTEGER,
    "status" "StopStatus" NOT NULL DEFAULT 'UNASSIGNED',
    "lat" DOUBLE PRECISION NOT NULL,
    "lng" DOUBLE PRECISION NOT NULL,
    "addressLine" TEXT NOT NULL,
    "label" TEXT,
    "placementNote" TEXT,
    "accessNotes" TEXT,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "estimatedMinutes" INTEGER NOT NULL DEFAULT 4,
    "needsReview" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Stop_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UiCopy" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "eventId" TEXT,
    "locale" TEXT NOT NULL DEFAULT 'en',
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updatedBy" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UiCopy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" BIGSERIAL NOT NULL,
    "orgId" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "before" JSONB,
    "after" JSONB,
    "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ipHash" TEXT,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");

-- CreateIndex
CREATE INDEX "Membership_userId_idx" ON "Membership"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Membership_orgId_userId_role_eventId_key" ON "Membership"("orgId", "userId", "role", "eventId");

-- CreateIndex
CREATE UNIQUE INDEX "Event_orgId_slug_key" ON "Event"("orgId", "slug");

-- CreateIndex
CREATE INDEX "Household_orgId_lat_lng_idx" ON "Household"("orgId", "lat", "lng");

-- CreateIndex
CREATE INDEX "Stop_eventId_routeId_sequence_idx" ON "Stop"("eventId", "routeId", "sequence");

-- CreateIndex
CREATE UNIQUE INDEX "UiCopy_orgId_eventId_locale_key_key" ON "UiCopy"("orgId", "eventId", "locale", "key");

-- CreateIndex
CREATE INDEX "AuditLog_orgId_at_idx" ON "AuditLog"("orgId", "at");

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Event" ADD CONSTRAINT "Event_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Household" ADD CONSTRAINT "Household_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Stop" ADD CONSTRAINT "Stop_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Stop" ADD CONSTRAINT "Stop_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE SET NULL ON UPDATE CASCADE;
